### ISSUE TITLE
Creating Personal Wiki Page for Ümmü Sena Özpınar

### ISSUE THREAD

**Issue by senaozpinar** [bounswe/bounswe2022group9#10]
Personal Wiki Page of Ümmü Sena Özpınar containing general information, contact information, programming languages and interests will be created and edited. Additional information can be added with time.

**Comment by senaozpinar** [comment]
Page was created.

**Comment by ozdemirfurkan** [comment]
You can add the link of your personal page to the sidebar.

**Comment by omersisman** [comment]
I have added the link of your page to the sidebar.

**Comment by senaozpinar** [comment]
General information, contact information, details about programming languages and interests were added.
