### ISSUE TITLE
Creating Favorite Repositories Page for Wiki

### ISSUE THREAD

**Issue by ozdemirfurkan** [bounswe/bounswe2022group9#12]
A template for favorite repositories will be added to wiki page. This page will consist of everyone's favorite page and the explanation of it.

**Comment by ozdemirfurkan** [comment]
The template is created. Group members can fill their parts now.

**Comment by omersisman** [comment]
I have added my favorite repository to the template.

**Comment by berkecaliskan** [comment]
I have added my favorite repository

**Comment by canbora** [comment]
I have added my favorite repository.

**Comment by berkkant** [comment]
I have added my favorite repository

**Comment by burakaktan** [comment]
I have added my favourite repository and some information about.it.

**Comment by kutaysaran** [comment]
I have added my favorite repository.

**Comment by cemsarpkaya** [comment]
added

**Comment by ozdemirfurkan** [comment]
Every member in the group wrote his/her favorite page.
