### ISSUE TITLE
Updating Wiki Homepage

### ISSUE THREAD

**Issue by oguzhanozboyaci** [bounswe/bounswe2022group9#237]
Updating wiki homepage according to former group members, new group members and their personal wikipages.

**Comment by oguzhanozboyaci** [comment]
I created my own wikipage and updated necessary places.

**Comment by utulb** [comment]
I created my own personal page and the links were added to the proper places.
[**personal-wiki-page**](https://github.com/bounswe/bounswe2022group9/wiki/Ufuk-Karagozl)
