### ISSUE TITLE
Selecting or Deciding Communicator of The Group

### ISSUE THREAD

**Issue by utulb** [bounswe/bounswe2022group9#238]
The communicator of the group should be decided on the mutual idea of the group or should be selected by @yagmurgoktas until the next CmpE451 Lab session.

After the decision, you should notify the assistants of the lab session.

**Deadline**:  11.10.2022

**Comment by yagmurgoktas** [comment]
I will be the communicator this semester. I will tell the assistants in the lab session.

**Comment by yagmurgoktas** [comment]
I talked to assistant of course.
