### ISSUE TITLE
Revising Sequence Diagrams

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#244]
Deadline: 11.10.2022 23:59

[UML Sequence Diagrams in the repository] (https://github.com/bounswe/bounswe2022group9/wiki/Sequence-Diagrams) were prepared long time ago and some revisions and modifications are needed on these diagrams.

TODO:
- [x] Delete "Sign Up with Google" sequence diagram.
- [x] Delete "Login with Google" sequence diagram.
- [x] Delete "Bid" sequence diagram.

The reason of these deletions are meeting decisions on 16th of October 2022. In this meeting, the group is decided to not implement bid feature (it is an optional feature) and don't use Google as an authentication service (authentication with email verification is enough).

**Comment by cwtaras** [comment]
I removed the unnecessary diagrams according to meeting decisons.
