### ISSUE TITLE
Creating Project Plan on ProjectLibre

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#249]
Deadline: 18.10.2022 13.59

TODO:

- [x] The project plan created during [Meeting-2](https://github.com/bounswe/bounswe2022group9/wiki/Meeting-Notes-1) will be transferred to ProjectLibre.
- [x] The plan will be added on the repository.

**Comment by utulb** [comment]
The project plan's screenshots and the pod file were added to the resources folder. Also, the updated project plan was added to the wiki page.
