### ISSUE TITLE
Elicitation of non-functional requirements

### ISSUE THREAD

**Issue by canbora** [bounswe/bounswe2022group9#25]
Deadline: 15.03.2022 11.00

TODO:

- The non-functional requirements of the Art Community Platform project will be elicitated from the [project description](https://github.com/bounswe/bounswe2022group9/blob/master/assignments/Art%20Community%20Platform.pdf), classified and added to the [requirement list](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#2-non-functional-requirements).
- Definitions of terms and notions that can create ambiguity in the requirement list will be added to the [glossary](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#glossary).
- Parts of the project description that are missing, ambiguous or not clear enough will be added to the [question list](https://github.com/bounswe/bounswe2022group9/wiki/Project-Questions).

**Comment by canbora** [comment]
I have examined the project description and added my list of non-functional requirements and questions. Words still need to be added to the glossary and more non-functional requirements could be added.

**Comment by berkkant** [comment]
I have also examined the project description and added my list of non-functional requirements and questions. Words still need to be added to the glossary and more non-functional requirements could be added.

**Comment by TurkerErdem99** [comment]
[Non-func. requirements](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#2-non-functional-requirements) are extended, some typos are fixed. [Glossary](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#glossary) is updated based on non-func. requirements.

**Comment by canbora** [comment]
Closed.
