### ISSUE TITLE
Introduction to React Native

### ISSUE THREAD

**Issue by yagmurgoktas** [bounswe/bounswe2022group9#250]
We decided to use React Native to develop mobile application. Before we get our hands dirty , we should expand our knowledge base. That's why we should review the following resources with my friends who will work on mobile.

Sources : 
* https://reactnative.dev/docs/getting-started
* https://docs.expo.dev/
* https://www.youtube.com/watch?v=0-S5a0eXPoc
* https://www.youtube.com/watch?v=VozPNrt-LfE

Deadline : 22.10.2022 17.00

**Comment by cwtaras** [comment]
We made our research and went through what we have learned. We are good to start implementing our app.
