### ISSUE TITLE
[Mobile] - Login/Signup Pages Implementations 

### ISSUE THREAD

**Issue by cwtaras** [bounswe/bounswe2022group9#252]
We should create our first pages of mobile app. I (@cwtaras ) will write initial login page and backbone of app. After that we can add signup page and forget password page. Finally, we should add mockup home and profile pages.

- [x] Login Page/ Initial commit - @cwtaras 
- [x] Signup Page - @yagmurgoktas 
- [x] Forget Password Page - @oguzhanozboyaci 
- [x] Mockup Pages - @cwtaras , @yagmurgoktas , @oguzhanozboyaci 
Deadline: 25.10.2022 22.00

**Comment by yagmurgoktas** [comment]
https://github.com/bounswe/bounswe2022group9/tree/feature/signup here is my branch to create signup page

**Comment by yagmurgoktas** [comment]
https://github.com/bounswe/bounswe2022group9/pull/265

**Comment by cwtaras** [comment]
We finalized this pages hence we can close this issue.
