### ISSUE TITLE
[Mobile] - Determining background, primary and secondary colors for mobile application

### ISSUE THREAD

**Issue by yagmurgoktas** [bounswe/bounswe2022group9#256]
As an art platform, such a simple interface did not make much sense to me. I think we should determine a theme together and choose the appropriate background , primary and secondary colors and we can create a design. As teammates, I expect your contribution as well. 

Deadline : 24.10.2022 , 00:00

**Comment by cwtaras** [comment]
https://www.schemecolor.com/wp-content/themes/colorsite/include/cc6.php?color0=173679&color1=4888c8&color2=7fc5dc&color3=e8e163&color4=db901c&color5=0b1e38&pn=Starry%20Starry%20Night

I think we can use this color scheme. If both of you accept, I will add this as color constants.

**Comment by cwtaras** [comment]
see: https://github.com/bounswe/bounswe2022group9/pull/261
I will close this issue once the PR is merged.
