### ISSUE TITLE
[Backend] Implement Login Feature

### ISSUE THREAD

**Issue by berkkant** [bounswe/bounswe2022group9#264]
Deadline: 28.10.2022 23.59

Users shall be able to log in the system by giving their username and a password.

TODO:

 Open a new feature branch called "login backend". It's a good practice to opening a branch to add a new feature to the system.
 Create an API end point accepting POST requests. Endpoint URL should be "{base_url}/user/login". When a request to this endpoint is received, login user with username and password in the request if username and password is compatible.
 If any field in the request (e.g., username) is missing 400 Http Status Code.
(https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#42-security) for further reference.

**Comment by omersisman** [comment]
There is another issue created and closed for this issue. So it can be closed.
