### ISSUE TITLE
[Milestone] Creating frontend scenario for signup

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#290]
Deadline: 01.11.2022 11.59

TODO:

- [x] Slides of the scenario which have cases like validation of username/email/password and a successful sing up process will be created to be presented in the Customer Presentation 1.

**Comment by burakaktan** [comment]
Ömer and me (Burak) made an online meeting and decided scenario content.
It's typed into a markdown file, [it is reachable from here](https://github.com/bounswe/bounswe2022group9/wiki/Milestone-1-Scenario-1)

**Comment by omersisman** [comment]
Slides will not be prepared as decision of the team. So I am closing the issue since it is done.
