### ISSUE TITLE
Deliverables Image View Issue

### ISSUE THREAD

**Issue by busraoguzoglu** [bounswe/bounswe2022group9#328]
Some images on the report cannot be viewed (check UML diagrams, Mockups). Please check them and make necessary adjustments.

**Comment by omersisman** [comment]
Images were ok when we submitted the report but now they're missing because of the website we have used for hosting our images. Now we're taking action and started to make adjustments. We will be updating you from here when we have fixed the issues as soon as possible.

**Comment by burakaktan** [comment]
In "sharing an art" scenario and mockup, two images were broken (because of the image hosting website we used), they are fixed now.
[Here is the link for updated page](https://github.com/bounswe/bounswe2022group9/wiki/%22Sharing-an-art%22)

**Comment by ozdemirfurkan** [comment]
Class Diagram images are re-uploaded to [wiki page](https://github.com/bounswe/bounswe2022group9/wiki/Class-Diagram) as I mentioned in the issue #329 .

**Comment by omersisman** [comment]
Use Case and Sequnce Diagram images are re-uploaded. Therefore I am closing the issue.
