### ISSUE TITLE
[Backend] Update Profile Picture

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#360]
Deadline: 02.12.2022

Users shall be able to update their profile pictures. In the beginning, the system gives a default profile picture to users, user may want to change it.

TODO:
- [ ] Implement an endpoint, accepting PUT requests, updating related user's profile picture. Profile picture should be uploaded to a third party service (imgbb API), and uploaded link should be stored.

**Comment by omersisman** [comment]
No need for seperate endpoint for this. As we talked in last meeting mobile/frontend will send base64 encoded image in body, therefore adding a string filed to -if there is no- update-profile endpoint is well enough.
