### ISSUE TITLE
[Backend] Recommending "Users To Follow" to Users

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#492]
Deadline: 23.12.2022 23.59

The "Artie" app should recommend "users to follow" to the users in the system. This feature will help users to find other users sharing similar interests and will make using the application more fun.
We will separate users into 2 parts:
1) Users didn't use the system enough (i.e., following less than 3 users): For this users, we will recommend the users having most followers
2) Users following more than (or equal to) 3 other users: For this users, we will recommend them to follow the users having at least one follower that is followed by the user (user that will receive recommendation). As an example, if userA follows userB and userB follows userC, the system will recommend userA to follow userC.

Don't forget that we'll not recommend to follow a user which is already being followed.

TODO:
- [x] Implement a helper function returning most popular users in the system (i.e., the users having the highest number of followers)
- [x] Implement a helper function getting a user id as a parameter returning users having at least one follower that is followed by the user with the given id.
- [x] Implement a new endpoint called "recommend_users_to_follow", this endpoint should decide whether the user is following less than 3 users or not and pick the related algorithm (from algorithms listed above), and return the "recommended users to follow" as a list in JSON format.

**Comment by berkkant** [comment]
I have implemented all the features. Now I am closing.
