### ISSUE TITLE
[Backend] Implement User Levels

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#494]
Deadline: 23.12.2022 23.59

According the [requirement 3.1.4.5](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#314-profile) "Users shall have levels on their profile based on the number of comments and number of shared art items.". 
Adding levels to the profiles of the users will be an awarding mechanism, and encourage users to share more art items (in terms of both quality and quantity, while more art items condition increases the quantity, more comments condition will increase the quality (e.g., users may share more labored arts to receive more comments))
This feature will also help users to find active users in the system.

Looking at the requirement mentioned at the beginning of issue, 
Level of a User = ((number of comments) + (number of shared art items)) / 50
is an appropriate formula to calculate the level of a user.

TODO:
- [ ] In "get_users" and "get_profile_info" endpoints -in addition to information returned currently- return levels of the users.

**Comment by omersisman** [comment]
I have started implementing this issue. Thanks for detailed description.

**Comment by omersisman** [comment]
I have completed development and opened a PR #509. I have also updated unit tests. This issue will automatically be closed after the PR is merged.
