### ISSUE TITLE
[Documentation] Documentation of API Endpoints

### ISSUE THREAD

**Issue by omersisman** [bounswe/bounswe2022group9#515]
We have a documentation for API endpoints in [documantation](https://documenter.getpostman.com/view/21597705/2s8YmSqfTg). Since Postman generates a readable documentation for endpoints in an easy way, there is no need for writing documentations in wiki pages. The link I have attached contains nearly all of the endpoints so far. Please when you create or update an endpoint, send your CURL request under this issue as a comment instead of writing documentations to wiki pages. So I can add them to our real documentation.

**Comment by omersisman** [comment]
Please check the [link](https://documenter.getpostman.com/view/21597705/2s8YmSqfTg) and send CURL requests missing there.

**Comment by burakaktan** [comment]
CURL comment for art item recommendation endpoint
>curl --location --request GET 'http://127.0.0.1/api/v1/recommend/art-items/3' \
 --header 'Cookie: csrftoken=oghkEx99VD87EOnBho9a3yPRt5tnsxFPVPePYFQklqR7aVy50TVQm06z0J969XIa'

**Comment by omersisman** [comment]
Thanks Burak, I have added your CURL and the requests related to Annotations. Therefore I am closing this issue.

**Comment by burakaktan** [comment]
I was send an example request for art item recommendation but not user recommendation. Let me also send an example request for user recommendation:

curl --location --request GET 'http://127.0.0.1/api/v1/recommend/user/1' \
--header 'Authorization: 5faaaa066935ceb6aad9b132cf4539e3e8a30b076f79d03aa9b7f7bb56fd1c18' \
--header 'Cookie: csrftoken=oghkEx99VD87EOnBho9a3yPRt5tnsxFPVPePYFQklqR7aVy50TVQm06z0J969XIa' \
--data-raw ''

**Comment by burakaktan** [comment]
Here is an example request for Notification endpoint. This endpoint returns notifications coming to the user with given id:

> curl --location --request GET 'http://127.0.0.1/api/v1/notification/4' \
--header 'Cookie: csrftoken=oghkEx99VD87EOnBho9a3yPRt5tnsxFPVPePYFQklqR7aVy50TVQm06z0J969XIa'
