### ISSUE TITLE
Extra Meeting on Recommendation Feature - Burak and Berkkant

### ISSUE THREAD

**Issue by burakaktan** [bounswe/bounswe2022group9#518]
Recommendation issues are created by Burak Ferit Aktan and some of them are assigned to him, some of them are assigned to Berkkant Koç.
During the implementation process, we faced some bugs, errors, and problems; and fortunately we solved them. And we decided to meet and review each other's codes.

Time: 18.00-19.30 and 20.30-21.00
Place: Discord (Online)

Objective of this meeting:
* Running recommendation related endpoints in our locals and test them with different requests using Postman.
* Talking about Burak Ferit Aktan's review message on [this PR](https://github.com/bounswe/bounswe2022group9/pull/511)

**Comment by berkkant** [comment]
We had a great meeting with Burak. We have worked on [this](https://github.com/bounswe/bounswe2022group9/pull/511) pull request and made it work.

We used postman to test our endpoints.
